User/urls.py
from django.conf.urls import url
from User import views
from django.contrib import admin
from .views import (
    PostLikeAPIToggle,

    )


app_name = 'User'

urlpatterns=[
        url(r'^home/$',views.userhome,name='home'),
        url(r'^(?P<slug>[\w-]+)likesupdate/$',views.Likesupdate,name='likesupdate'),
        url(r'^(?P<slug>[\w-]+)details/$',views.showitem,name='details'),
        # url(r'^(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like-toggle'),
        url(r'^api/(?P<slug>[\w-]+)/likes/$',PostLikeAPIToggle.as_view(),name='likes-api-toggle'),
        url(r'^profile/$',views.userprofile,name='profile'),
        url(r'^sellitem/$',views.sellitem,name='sellitem'),
        url(r'^post/$', views.Post, name='post'),
        url(r'^comment/$', views.Comment, name='comment'),
        url(r'^notification/$', views.Notifications, name='notification'),
        url(r'^messages/$', views.Messages, name='messages'),



]

firstapp/urls.py
from django.conf.urls import url
from firstapp import views


app_name = 'firstapp'

urlpatterns=[



        url(r'^register/$',views.register,name='register'),
        url(r'^login/$',views.userlogin,name='login'),
        url(r'^error_404/$',views.error_404,name='error_404'),
        url(r'^error_500/$',views.error_500,name='error_500'),

        






]

onlinefleamart1/urls.py
from django.conf.urls import url
from django.contrib import admin
from firstapp import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404,handler500
# handler403 = 'firstapp.views.permission_denied'
# handler404 = 'firstapp.views.page_not_found'
# handler500 = 'firstapp.views.server_error'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^fleamart/',include('firstapp.urls')),
    url(r'^User/',include('User.urls',namespace="User")),

    # url(r'^$',include('firstapp.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^logout/$',views.userlogout,name='logout'),



    # url(r'^login/', views.login,name='login'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'firstapp.views.error_404'
handler500 = 'firstapp.views.error_500'

firstapp/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    portfolio = models.URLField(blank=True)
    profilepic = models.ImageField(upload_to='profilepics',blank=True)
    address = models.TextField(blank=True)
    
    def get_name(self):
        return self.user.username
    def get_some(self):
        return self.profilepic
    def get_absolute_url(self):
        return reverse("username", kwargs={"username": self.user.username})

firstapp/forms.py
from django.contrib.auth.models import User
from django import forms
from firstapp.models import UserProfileInfo



class UserForm(forms.ModelForm):
    
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInform(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('address','portfolio','profilepic')

firstapp/views.py
from django.shortcuts import render,redirect
from firstapp.forms import UserForm,UserProfileInform

from .models import UserProfileInfo,User
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login as auth_login,logout
from User.models import SellItemInfo

def error_404(request):
    return render(request,'firstapp/404.html')

def error_500(request):
    return render(request,'firstapp/404.html')

def index(request):
    items = SellItemInfo.objects.all()
    args = {'items' : items}
    return render(request,'firstapp/index.html', args,)



@login_required
def userlogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        userform = UserForm(data=request.POST)
        profileform = UserProfileInform(data=request.POST)

        if userform.is_valid() and profileform.is_valid():
            user = userform.save()
            user.set_password(user.password)
            user.save()

            profile = profileform.save(commit=False)
            profile.user = user

            if 'profilepic' in request.FILES:
                profile.profilepic = request.FILES['profilepic']

            profile.save()
            registered = True

        else :
            print('Not possible')
    else:
        userform = UserForm()
        profileform = UserProfileInform()

    return render(request,'firstapp/registration.html',
    {
        'userform':userform,
        'profileform':profileform,
        'registered':registered
    })


def userlogin(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        global userName

        userName = username
        user = authenticate(username=username,password=password)


        if user:
            if user.is_active:
                auth_login( request , user )
                return redirect('/User/home/')
            else:
                return HttpResponse("Account is not active")
        else:
            context = {
                'Notice':'Please User Correct UserName or Password'

            }
            return render(request,'firstapp/login.html',context)
    else:
        return render(request,'firstapp/login.html')

templates/firstapp/Speech to text converter in JS.html
<!DOCTYPE html>
<html>
	<head>
		<title>Speech to text converter in JS</title>
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.1/css/font-awesome.min.css" />
		<style type="text/css">
			body{
				font-family: verdana;
			}
			#result{
				height: 200px;
				border: 1px solid #ccc;
				padding: 10px;
				box-shadow: 0 0 10px 0 #bbb;
				margin-bottom: 30px;
				font-size: 14px;
				line-height: 25px;
			}
			button{
				font-size: 20px;
				position: absolute;
				top: 240px;
				left: 50%;
			}
		</style>
	</head>
	<body>
		<h4 align="center">Speech to text converter in JS</h4>
		<div id="result"></div>
		<button onclick="startConverting();"><i class="fa fa-microphone"></i></button>
		<script type="text/javascript">

			var r = document.getElementById('result');

			function startConverting () {
				if('webkitSpeechRecognition' in window){
					var speechRecognizer = new webkitSpeechRecognition();
					speechRecognizer.continuous = true;
					speechRecognizer.interimResults = true;
					speechRecognizer.lang = 'en-IN';
					speechRecognizer.start();

					var finalTranscripts = '';

					speechRecognizer.onresult = function(event){
						var interimTranscripts = '';
						for(var i = event.resultIndex; i < event.results.length; i++){
							var transcript = event.results[i][0].transcript;
							transcript.replace("\n", "<br>");
							if(event.results[i].isFinal){
								finalTranscripts += transcript;
							}else{
								interimTranscripts += transcript;
							}
						}
						r.innerHTML = finalTranscripts + '<span style="color:#999">' + interimTranscripts + '</span>';
					};
					speechRecognizer.onerror = function (event) {
					};
				}else{
					r.innerHTML = 'Your browser is not supported. If google chrome, please upgrade!';
				}
			}

			

		</script>
	</body>
</html>

templates/firstapp/basic.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'firstapp:register' %}">Register</a></li>



        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

templates/firstapp/index.html
<!DOCTYPE html>
{% extends "firstapp/base2.html" %}
{% load static from staticfiles %}


  {% block body_block %}

        <!-- BEGIN SERVICE BOX -->
        <div class="row service-box margin-bottom-40">
          <div class="col-md-4 col-sm-4">
            <div class="service-box-heading">
              <em><i class="fa fa-location-arrow blue"></i></em>
              <span>Fastest Online Shoping</span>
            </div>
            <p>Lorem ipsum dolor sit amet, dolore eiusmod quis tempor incididunt ut et dolore Ut veniam unde nostrudlaboris. Sed unde omnis iste natus error sit voluptatem.</p>
          </div>
          <div class="col-md-4 col-sm-4">
            <div class="service-box-heading">
              <em><i class="fa fa-check red"></i></em>
              <span>Quality is the main factor</span>
            </div>
            <p>Lorem ipsum dolor sit amet, dolore eiusmod quis tempor incididunt ut et dolore Ut veniam unde nostrudlaboris. Sed unde omnis iste natus error sit voluptatem.</p>
          </div>
          <div class="col-md-4 col-sm-4">
            <div class="service-box-heading">
              <em><i class="fa fa-compress green"></i></em>
              <span>Smart Online Marketing</span>
            </div>
            <p>Lorem ipsum dolor sit amet, dolore eiusmod quis tempor incididunt ut et dolore Ut veniam unde nostrudlaboris. Sed unde omnis iste natus error sit voluptatem.</p>
          </div>
        </div>
        <!-- END SERVICE BOX -->


        <!-- BEGIN RECENT WORKS -->
        <div class="row recent-work margin-bottom-40">
          <div class="col-md-3">
            <h2><a href="portfolio.html">Recent Uploaded Products</a></h2>
            <p></p>
          </div>
          <div class="col-md-9">
            <div class="owl-carousel owl-carousel3">
                {% for item in items %}
                    <div class="recent-work-item">
                      <em>
                        <img src="{{ item.item_pic.url }}" alt="Amazing Project" class="img-responsive">
                        <a href="{% url 'firstapp:login' %}"><i class="fa fa-link"></i></a>
                        <a href="{{ item.item_pic.url }}" class="fancybox-button" title="{{ item.item_name }}" data-rel="fancybox-button"><i class="fa fa-search"></i></a>
                      </em>
                      <a class="recent-work-description" href="javascript:;">
                        <strong>{{ item.item_name }}</strong>
                        <b>{{ item.item_location }}</b>
                      </a>
                    </div>
                {% endfor %}


            </div>
          </div>
        </div>
        <!-- END RECENT WORKS -->

        <!-- BEGIN TABS AND TESTIMONIALS -->
        <div class="row mix-block margin-bottom-40">
          <!-- TABS -->
          <div class="col-md-7 tab-style-1">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#tab-1" data-toggle="tab">Multipurpose</a></li>
              <li><a href="#tab-2" data-toggle="tab">Documented</a></li>
              <li><a href="#tab-3" data-toggle="tab">Responsive</a></li>
              <li><a href="#tab-4" data-toggle="tab">Clean & Fresh</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane row fade in active" id="tab-1">
                <div class="col-md-3 col-sm-3">
                  <a href="assets/temp/photos/img7.jpg" class="fancybox-button" title="Image Title" data-rel="fancybox-button">
                    <img class="img-responsive" src="assets/pages/img/photos/img7.jpg" alt="">
                  </a>
                </div>
                <div class="col-md-9 col-sm-9">
                  <p class="margin-bottom-10">Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Cosby sweater eu banh mi, qui irure terry richardson ex squid Aliquip placeat salvia cillum iphone.</p>
                  <p><a class="more" href="javascript:;">Read more <i class="icon-angle-right"></i></a></p>
                </div>
              </div>
              <div class="tab-pane row fade" id="tab-2">
                <div class="col-md-9 col-sm-9">
                  <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia..</p>
                </div>
                <div class="col-md-3 col-sm-3">
                  <a href="assets/temp/photos/img10.jpg" class="fancybox-button" title="Image Title" data-rel="fancybox-button">
                    <img class="img-responsive" src="assets/pages/img/photos/img10.jpg" alt="">
                  </a>
                </div>
              </div>
              <div class="tab-pane fade" id="tab-3">
                <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>
              </div>
              <div class="tab-pane fade" id="tab-4">
                <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>
              </div>
            </div>
          </div>
          <!-- END TABS -->

          <!-- TESTIMONIALS -->
          <div class="col-md-5 testimonials-v1">
            <div id="myCarousel" class="carousel slide">
              <!-- Carousel items -->
              <div class="carousel-inner">
                <div class="active item">
                  <blockquote><p>Life is one big road with lots of signs. So when you riding through the ruts, don't complicate your mind. Flee from hate, mischief and jealousy. Don't bury your thoughts, put your vision to reality. Wake Up and Live!</p></blockquote>
                  <div class="carousel-info">
                    <img class="pull-left" src="static/assets/pages/img/people/photo.jpg" alt="">
                    <div class="pull-left">
                      <span class="testimonials-name">Mainuddin Russel</span>
                      <span class="testimonials-post">Team Member</span>
                    </div>
                  </div>
                </div>
                <div class="item">
                  <blockquote><p>To be a champion, I think you have to see the big picture. It's not about winning and losing; it's about every day hard work and about thriving on a challenge. It's about embracing the pain that you'll experience at the end of a race and not being afraid. I think people think too hard and get afraid of a certain challenge.</p></blockquote>
                  <div class="carousel-info">
                    <img class="pull-left" src="static/assets/pages/img/people/img.jpg" alt="">
                    <div class="pull-left">
                      <span class="testimonials-name">Provakar Mandal</span>
                      <span class="testimonials-post">Team Member</span>
                    </div>
                  </div>
                </div>
                <!-- <div class="item">
                  <blockquote><p>Reprehenderit butcher stache cliche tempor, williamsburg carles vegan helvetica.retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid Aliquip placeat salvia cillum iphone.</p></blockquote>
                  <div class="carousel-info">
                    <img class="pull-left" src="assets/pages/img/people/img2-small.jpg" alt="">
                    <div class="pull-left">
                      <span class="testimonials-name">Jake Witson</span>
                      <span class="testimonials-post">Commercial Director</span>
                    </div>
                  </div>
                </div> -->
              </div>

              <!-- Carousel nav -->
              <a class="left-btn" href="#myCarousel" data-slide="prev"></a>
              <a class="right-btn" href="#myCarousel" data-slide="next"></a>
            </div>
          </div>
          <!-- END TESTIMONIALS -->
        </div>
        <!-- END TABS AND TESTIMONIALS -->



        <!-- BEGIN CLIENTS -->
        <div class="row margin-bottom-40 our-clients">
          <div class="col-md-3">
            <h2><a href="javascript:;">Our Clients</a></h2>
            <p>World's Famous people and comppanies are our clients</p>
          </div>
          <div class="col-md-9">
            <div class="owl-carousel owl-carousel6-brands">
              <div class="client-item">
                <a href="javascript:;">
                  <img src="static/assets/pages/img/clients/bakifade.jpg" class="img-responsive" alt="">
                  <img src="static/assets/pages/img/clients/nnn.jpg" class="color-img img-responsive" alt="">
                </a>
              </div>
              <div class="client-item">
                <a href="javascript:;">
                  <img src="static/assets/pages/img/clients/jjj.jpg" class="img-responsive" alt="">
                  <img src="static/assets/pages/img/clients/bxd.jpg" class="color-img img-responsive" alt="">
                </a>
              </div>
              <div class="client-item">
                <a href="javascript:;">
                  <img src="static/assets/pages/img/clients/iii.jpg" class="img-responsive" alt="">
                  <img src="static/assets/pages/img/clients/ddd.jpg" class="color-img img-responsive" alt="">
                </a>
              </div>


              <div class="client-item">
                <a href="javascript:;">
                  <img src="static/assets/pages/img/clients/kkk.jpg" class="img-responsive" alt="">
                  <img src="static/assets/pages/img/clients/photo.jpg" class="color-img img-responsive" alt="">
                </a>
              </div>
            </div>
          </div>
        </div>
        <!-- END CLIENTS -->
  {% endblock %}

templates/firstapp/invalid.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Invalid login</h1>
  </body>
</html>

templates/firstapp/login.html
<!DOCTYPE html>
{% extends "firstapp/base3.html" %}


  {% block body_block %}


        <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <!-- <li><>Pages</a></li> -->
            <li class="active"><a href="">Login</a></li>
        </ul>
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">
          <!-- BEGIN SIDEBAR -->
          <div class="sidebar col-md-3 col-sm-3">
            <ul class="list-group margin-bottom-25 sidebar-menu">
              <!-- <li class="list-group-item clearfix"><a href="#"><i class="fa fa-angle-right"></i>Login/Register</a></li>
              <li class="list-group-item clearfix"><a href="javascript:;"><i class="fa fa-angle-right"></i> Restore Password</a></li>
              <li class="list-group-item clearfix"><a href="javascript:;"><i class="fa fa-angle-right"></i> My account</a></li>
              <li class="list-group-item clearfix"><a href="javascript:;"><i class="fa fa-angle-right"></i> Address book</a></li>
              <li class="list-group-item clearfix"><a href="javascript:;"><i class="fa fa-angle-right"></i> Wish list</a></li>
              <li class="list-group-item clearfix"><a href="javascript:;"><i class="fa fa-angle-right"></i> Returns</a></li>
              <li class="list-group-item clearfix"><a href="javascript:;"><i class="fa fa-angle-right"></i> Newsletter</a></li>
            </ul> -->
          </div>
          <!-- END SIDEBAR -->

          <!-- BEGIN CONTENT -->
          <div class="col-md-9 col-sm-9">
            <h1>Login</h1>
            <div class="content-form-page">
              <div class="row">
                <div class="col-md-7 col-sm-7">


            <form class="form-horizontal form-without-legend" role="form" method="post" action="{% url 'firstapp:login'   %}">
              {% csrf_token %}
                    <div class="form-group">
                      <label for="email" class="col-lg-4 control-label">User Name <span class="require">*</span></label>
                      <div class="col-lg-8">
                        <input id="username" type="text" class="form-control" placeholder="username" name="username" />
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="password" class="col-lg-4 control-label">Password <span class="require">*</span></label>
                      <div class="col-lg-8">
                        <input id="password" type="password" class="form-control" placeholder="password" name="password" />
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-8 col-md-offset-4 padding-left-0">
                        <a href="page-forgotton-password.html">Forget Password?</a>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-8 col-md-offset-4 padding-left-0">
                        <a href="page-forgotton-password.html">{{ Notice }}</a>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-8 col-md-offset-4 padding-left-0 padding-top-20">
                        <button type="submit" class="btn btn-success" value="Login">Login</button>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-8 col-md-offset-4 padding-left-0 padding-top-10 padding-right-30">
                        <hr>
                        <div class="login-socio">
                            <p class="text-muted">or login using:</p>
                            <ul class="social-icons">
                                <li><a href="javascript:;" data-original-title="facebook" class="facebook" title="facebook"></a></li>
                                <li><a href="javascript:;" data-original-title="Twitter" class="twitter" title="Twitter"></a></li>
                                <li><a href="javascript:;" data-original-title="Google Plus" class="googleplus" title="Google Plus"></a></li>
                                <li><a href="javascript:;" data-original-title="Linkedin" class="linkedin" title="LinkedIn"></a></li>
                            </ul>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-8 col-md-offset-4 padding-left-0 padding-top-20">
                        <input type="hidden" name="next" value="/home/" />
                      </div>
                    </div>
                  </form>


                </div>
                <div class="col-md-4 col-sm-4 pull-right">
                  <div class="form-info">
                    <h2><em>Important</em> Information</h2>
                    <p>If you find any kind of system fault please inform us at <kbd>fleamart@gmail.com</kbd>.</p>

                    <button type="button" class="btn btn-primary">More details</button>
                  </div>
                </div>
              </div>
            </div>


              </div>

            </div>
          </div>
          </div>
          <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
      {% endblock %}

templates/firstapp/messages.html
{% for obj in chat %}
    {% if obj.user == request.user %}
    <li class="cont">
        <img src="{{ obj.user.userprofileinfo.profilepic.url }}" alt="Avatar" class="right" style="width:100%;">
        <p>{{ obj.user }} : {{ obj.message }}</p>
        <span class="time-left">  {{ obj.created }}</span>
    </li>


    {% elif request.user.username == obj.fromm  %}
        <li class="cont darker">
            <img src="{{ obj.user.userprofileinfo.profilepic.url }}" alt="Avatar"  style="width:100%;">
            <p>{{ obj.user }} : {{ obj.message }}</p>
            <span class="time-right">{{ obj.created }}</span>
        </li>
        <!-- <li class="b text-left list-group-item">
          <img src="{{ obj.user.userprofileinfo.profilepic.url }}" height="50%" width="50%" class="img-responsive" alt="Mountains">
          {{ obj.user }} : {{ obj.message }}</br>
          {{ obj.created }}
         </li> -->
    {% elif other == request.user.username  %}
        <li class="b text-left list-group-item">
          <img src="{{ obj.user.userprofileinfo.profilepic.url }}" height="50%" width="50%" class="img-responsive" alt="Mountains">
          {{ obj.user }} : {{ obj.message }}</br>
          {{ obj.created }}
        </li>
    {% endif %}
{% empty %}
    <li class="text-right list-group-item">No messages yet!</li>
{% endfor %}

templates/firstapp/notification.html
{% for obj in counter %}
    <!-- {% if other == obj.user.username %} -->
        <a>{{ obj.to }}->{{ obj.description }}</a>
    <!-- {% endif %} -->
{% empty %}
      <a>00</a>
{% endfor %}

templates/firstapp/profile.html
<!DOCTYPE html>
{% extends "firstapp/base4.html" %}
{% load static from staticfiles %}

  {% block body_block %}

        <ul class="breadcrumb">

            <li><a href="{% url 'User:home' %}">{{ user }} Home</a></li>
            <li class="active"><a href="">{{ user }} Profile</a></li>
        </ul>





        <div class="row margin-bottom-40">
  <!-- BEGIN SIDEBAR -->
  <div class="sidebar col-md-3 col-sm-3">
    <ul class="list-group margin-bottom-25 sidebar-menu">
        <h1>Profile</h1>
      {% if user.userprofileinfo.profilepic %}
        <img src="{{ user.userprofileinfo.profilepic.url }}" width="240">
      {% endif %}
    <br>
    <br>
      <li class="list-group-item clearfix"><a href="#"><i class="fa fa-angle-right"></i>  <p>Username: {{ user }}</p> </a></li>
      <li class="list-group-item clearfix"><a href="javascript:;"><i class="fa fa-angle-right"></i> <p>Email: {{ user.email }}</p> </a></li>
      <li class="list-group-item clearfix"><a href="javascript:;"><i class="fa fa-angle-right"></i> <p>Address: {{ user.userprofileinfo.address }}</p> </a></li>
      <li class="list-group-item clearfix"><a href="javascript:;"><i class="fa fa-angle-right"></i> <p>Website: {{ user.userprofileinfo.portfolio }}</p> </a></li>

    </ul>

  </div>
  <!-- END SIDEBAR -->

  <!-- BEGIN CONTENT -->
  <div class="col-md-6 col-sm-6">
      <h2>Recent Uploaded Products</h2>
      <div class="content-page">
          <div class="filter-v1">
            {% for item in items %}
            <div class="row mix-grid thumbnails">
                <div class="col-md-6 col-sm-8 mix category_1 mix_all" style="display: block; opacity: 1; ">
                  <div class="mix-inner">
                    <img alt="" src="{{ item.item_pic.url }}" class="img-responsive">

                    <div class="mix-details">
                       <h4>{{ item.item_name }}</h4>
                       <a class="mix-link"><i class="">{{ item.item_usetime }}</i></a>
                       <a title="{{ item.item_location }}" href="{{ item.item_pic.url }}" class="mix-preview fancybox-button"><i class="fa fa-search"></i></a>
                    </div>
                  </div>
                </div>
            </div>
            {% endfor %}
          </div>
      </div>
  </div>

  <div class="col-md-3 col-sm-3 pull-right">
        <div class="form-info">
          <h2><em>Important</em> Information</h2>
          <p>If you find any kind of system fault please inform us at <kbd>fleamart@gmail.com</kbd>.</p>

          <button type="button" class="btn btn-primary">More details</button>
        </div>
      </div>
  </div>
  <!-- END CONTENT -->

{% endblock %}